name: Doxygen

on:
  push:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen
        run: |
          sudo apt-get install -y doxygen
          doxygen -g Doxyfile
          doxygen Doxyfile

      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          doxyfile-path: ./Doxyfile

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./